[phases.setup]
nixPkgs = ["apacheHttpd", "php", "composer", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "composer install --ignore-platform-reqs", # Composer to install PHP dependencies
    "chmod +x /assets/start.sh",
    "..."
]

[start]
cmd = '/assets/start.sh'

[staticAssets]
"start.sh" = '''
#!/bin/bash

# Apply Apache configuration
node /assets/scripts/prestart.mjs /assets/apache.template.conf /etc/apache2/apache2.conf

# Start supervisor
supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///assets/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-apache.conf" = '''
[program:worker-apache]
process_name=%(program_name)s_%(process_num)02d
command=apachectl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-apache.log
stderr_logfile=/var/log/worker-apache.log
'''

"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
process_name=%(program_name)s_%(process_num)02d
command=php-fpm -y /assets/php-fpm.conf -F
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

"worker-laravel.conf" = '''
[program:worker-laravel]
process_name=%(program_name)s_%(process_num)02d
command=bash -c 'exec php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=12
startsecs=0
stopwaitsecs=3600
stdout_logfile=/var/log/worker-laravel.log
stderr_logfile=/var/log/worker-laravel.log
'''

"php-fpm.conf" = '''
[www]
listen = 127.0.0.1:9000
user = www-data
group = www-data
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 50
pm.min_spare_servers = 4
pm.max_spare_servers = 32
pm.start_servers = 18
clear_env = no
'''

"apache.template.conf" = '''
ServerRoot "/etc/apache2"
Listen ${PORT}

<IfModule mpm_prefork_module>
    StartServers 5
    MinSpareServers 5
    MaxSpareServers 10
    MaxRequestWorkers 250
    MaxConnectionsPerChild 1000
</IfModule>

LoadModule php_module /nix/store/.../mod_php.so

<VirtualHost *:${PORT}>
    DocumentRoot "/app"
    <Directory "/app">
        AllowOverride None
        Require all granted
        Options Indexes FollowSymLinks
    </Directory>

    DirectoryIndex index.php
    AddType application/x-httpd-php .php

    <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
    </FilesMatch>

    ErrorLog /var/log/apache-error.log
    CustomLog /var/log/apache-access.log combined
</VirtualHost>
'''
